Update license copyright year to 2024 (#11)
## Changelog

- Update license copyright year to 2024

---

Powered by
[FantasticFiasco/action-update-license-year](https://github.com/FantasticFiasco/action-update-license-year)

---------

Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: fabasoad <fabasoad@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,21 +14,21 @@ runs:
   using: "composite"
   steps:
     - name: Fail
-      uses: actions/github-script@v7
       if: ${{ runner.os == 'Windows' }}
-      with:
-        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
+      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      shell: sh
     - name: Build version
       id: version
-      if: ${{ runner.os != 'Windows' }}
-      uses: actions/github-script@v7
-      with:
-        script: |
-          const a = '${{ inputs.version }}'.split('.');
-          return `y_${a[0]}_${a[1]}_${a[2]}`;
+      env:
+        INPUT_VERSION: "${{ inputs.version }}"
+      run: |
+        major="$(echo "${INPUT_VERSION}" | cut -d. -f1)"
+        minor="$(echo "${INPUT_VERSION}" | cut -d. -f2)"
+        patch="$(echo "${INPUT_VERSION}" | cut -d. -f3)"
+        echo "result=y_${major}_${minor}_${patch}" >> "$GITHUB_OUTPUT"
+      shell: sh
     - name: Collect info
       id: info
-      if: ${{ runner.os != 'Windows' }}
       run: |
         YORICK_INSTALLED=$(if command -v yorick >/dev/null 2>&1; then echo true; else echo false; fi)
         echo "YORICK_INSTALLED=$YORICK_INSTALLED" >> $GITHUB_OUTPUT
@@ -37,7 +37,7 @@ runs:
         echo "YORICK_VERSION=${{ steps.version.outputs.result }}" >> $GITHUB_OUTPUT
       shell: sh
     - name: Download yorick
-      if: ${{ runner.os != 'Windows' && steps.info.outputs.YORICK_INSTALLED == 'false' }}
+      if: ${{ steps.info.outputs.YORICK_INSTALLED == 'false' }}
       uses: actions/checkout@v4
       with:
         repository: LLNL/yorick
@@ -45,7 +45,7 @@ runs:
         fetch-depth: 1
         path: yorick
     - name: Install yorick
-      if: ${{ runner.os != 'Windows' && steps.info.outputs.YORICK_INSTALLED == 'false' }}
+      if: ${{ steps.info.outputs.YORICK_INSTALLED == 'false' }}
       run: |
         make install
         echo "${{ steps.info.outputs.YORICK_PATH }}/relocate/bin" >> $GITHUB_PATH
