Bump pre-commit-hooks from 4.6.0 to 5.0.0 (#14)
## Changelog

- Update license copyright year to 2025

---

Powered by
[FantasticFiasco/action-update-license-year](https://github.com/FantasticFiasco/action-update-license-year)

---------

Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: fabasoad <fabasoad@gmail.com>

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -2,25 +2,54 @@
 name: Functional Tests
 
 on: # yamllint disable-line rule:truthy
-  pull_request: {}
   push:
     branches:
-      - "main"
+      - main
+  pull_request:
+    paths:
+      - .github/workflows/functional-tests.yml
+      - src/**
+      - action.yml
+  schedule:
+    # Every Friday at 09:00 JST
+    - cron: "0 0 * * 5"
+  workflow_dispatch: {}
 
 defaults:
   run:
     shell: sh
 
 jobs:
+  get-versions:
+    name: Get 3 latest versions
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    outputs:
+      versions: ${{ steps.prepare-list.outputs.versions }}
+    steps:
+      - name: Prepare list
+        id: prepare-list
+        env:
+          RELEASES_AMOUNT: "3"
+          TARGET_REPO: "LLNL/yorick"
+        run: |
+          versions=$(curl -sL \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/${TARGET_REPO}/tags" \
+            | jq -c -r --arg n "${RELEASES_AMOUNT}" '[.[0:($n | tonumber)][].name] | . += ["latest"]')
+          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
   setup-yorick:
     name: Setup yorick
+    needs: [get-versions]
+    runs-on: ${{ matrix.os }}-latest
     timeout-minutes: 5
     strategy:
       fail-fast: false
       matrix:
-        runner: ["ubuntu-latest", "macos-12"]
-        version: ["2.2.04", "2.2.03", "2.2.02"]
-    runs-on: ${{ matrix.runner }}
+        os: ["ubuntu"]
+        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
@@ -30,3 +59,39 @@ jobs:
           version: ${{ matrix.version }}
       - name: Print version
         run: yorick --version
+  test-force:
+    name: Test force
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup yorick 1
+        id: setup-yorick-1
+        uses: ./
+        with:
+          version: "y_2_2_04"
+      - name: Setup yorick 2
+        id: setup-yorick-2
+        uses: ./
+        with:
+          version: "y_2_2_04"
+          force: ${{ matrix.force }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-yorick-1" \
+            "${{ steps.setup-yorick-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-yorick-2" \
+            "${{ steps.setup-yorick-2.outputs.installed }}" \
+            "${{ matrix.force }}"
